stages:
  - build
  - trigger

default:
  interruptible: true
  image: node

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_IID

create-branch:
  stage: build
  tags: 
    - docker-prod
  variables:
    DOWNSTREAM_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
    DOWNSTREAM_PROJECT_NAME: $DOWNSTREAM_PROJECT_NAME
  script:
    - |
      set -e
      #Creating a new branch
        curl --request POST --header \
        "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" \
        "${CI_SERVER_URL}/api/v4/projects/$DOWNSTREAM_PROJECT_ID/repository/branches?branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&ref=master" || echo "error creating branch $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"

downstream_bridge:
  stage: trigger
  variables:
    CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME: $CI_COMMIT_BRANCH
  trigger:
    project: $CI_PROJECT_NAMESPACE/sdk
    branch: $CI_COMMIT_BRANCH
    strategy: depend