name: Publish Packages

on:
    workflow_dispatch:
    push:
        branches:
            - release
            - master

env:
    nodeTestTimeout: 4000
    browserTestTimeout: 8000
    DETECT_CHROMEDRIVER_VERSION: true
    HARP_NO_HARD_SOURCE_CACHE: true

jobs:
    deploy:
        name: Deploy coresdk packages
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node
              run: echo $NODE_AUTH_TOKEN
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
